apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
- ../../base

patchesStrategicMerge:
- patches/ml-pipeline-viewer-template.yaml
- patches/service-account-annotations.yaml
