---
repos:
    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.26.1
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 21.5b2
      hooks:
          - id: black
