apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://external-secrets.github.io/kubernetes-external-secrets/
    targetRevision: 7.2.0
    chart: kubernetes-external-secrets
    helm:
      parameters:
        - name: "rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
          value: << role_arn.external_secrets_service >>
        - name: env.AWS_REGION
          value: << aws_region >>
        - name: env.AWS_DEFAULT_REGION
          value: << aws_region >>
        - name: env.POLLER_INTERVAL_MILLISECONDS
          value: "10000"
        - name: fullnameOverride
          value: external-secrets
        - name: securityContext.runAsNonRoot
          value: "true"
        - name: securityContext.fsGroup
          value: "1000"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
