apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/ReggieCarey/argoflow-aws.git
    # targetRevision: 177337816322/aim-city.pub.aws.mitre.org
=======
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
>>>>>>> parent of 5641767 (Configuration for AIM-City on AWS)
    path: ./distribution
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
