apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serving-core-v0_24_0.yaml
- net-istio-v0_24_0.yaml
# - eventing-core-v0_22_0.yaml # Eventing is optional
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.0/components.yaml # metrics server (needed for HPA)
- allow-all-ns-knative-authorization-policy.yaml
- peerauthentication.yaml
# - monitoring/

patchesStrategicMerge:
# patches
- patches/config-istio.yaml
- patches/config-logging.yaml
- patches/config-network.yaml
- patches/config-observability.yaml
- patches/domain-config.yaml
- patches/increase-deadline.yaml
- patches/enable-istio-injection.yaml
- patches/enable-sidecar-istio-controller.yaml

# removals
- removals/remove-knative-ingress-gateway.yaml
- removals/remove-knative-local-gateway.yaml




images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:bd48057f8d6e5f95f389225979c89d2d99d52a4876d2342fc033c909096d4698
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:d3d6f5ecfff577a6d4d5a0549379fa1acf1d66d7422a58b1756e40eba555285c
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  digest: sha256:fafa1afcc9f2c6e79b096ffbc67e14ff3f34e3591d887335811ca15970b3b837
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  digest: sha256:1335e57427a372d15e8a90a3370eaa6896c9cb3fd7cb6f2a63021cceaea2e8e6
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:e9503135b4b46a3700d91bdb32df60923575aaedbcc5192bdc3e41b64591ee50
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:e9b9cc7a2a091194161a7a256d6fc342317080f1a31e1f1a33993a5e1993fdb5
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  digest: sha256:41f58d7e8319e473dbf27dec3d329b631f03ec0899c98ba2dd3d3166a6fb7a42
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  digest: sha256:49bf045db42aa0bfe124e9c5a5c511595e8fc27bf3a77e3900d9dec2b350173c
- name: k8s.gcr.io/metrics-server/metrics-server
  newName: k8s.gcr.io/metrics-server/metrics-server
  newTag: v0.5.0
