apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serving-core-v0_24_0.yaml
- net-istio-v0_24_0.yaml
# - eventing-core-v0_22_0.yaml # Eventing is optional
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.0/components.yaml # metrics server (needed for HPA)
- allow-all-ns-knative-authorization-policy.yaml
- peerauthentication.yaml
# - monitoring/

patchesStrategicMerge:
# patches
- patches/config-istio.yaml
- patches/config-logging.yaml
- patches/config-network.yaml
- patches/config-observability.yaml
- patches/domain-config.yaml
- patches/increase-deadline.yaml
- patches/enable-istio-injection.yaml
- patches/enable-sidecar-istio-controller.yaml

# removals
- removals/remove-knative-ingress-gateway.yaml
- removals/remove-knative-local-gateway.yaml




images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:0fdd0f9e6a7698cf3ecec9494c46509109345476a99f21f4cc5117dff5c9dda4
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:f36d1a5e3b6bc385398224acf1ee14b3b93f4fa8c6ea8c9126e606a9e67092a0
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping
  digest: sha256:3189aa2179c2d199cd31328813ebae4507bc12d94bf21b9b0bc231d6cf09f83c
- name: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/domain-mapping-webhook
  digest: sha256:5d537e5c85a07173c495fff2984208c267a1a545910b6abb881c1f0016ff2038
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:e66b4851894e92898b0b3dc6d6fa74ac766ed1d1f85f4b55ac8076f8ae14301a
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:18ea69e9afc42a9a79d6959499fa5adfa880f3a0f0ffde55a0ea6814bd1bb8b6
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  digest: sha256:812673b9127af530272fdeb584f91486e8f7b4ef1ea49f5b43805560f8ca6986
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  digest: sha256:6f5032b1db2ecea984b713613f2af8b7aed9c4cd1bc033f208720b7d035f81f4
- name: k8s.gcr.io/metrics-server/metrics-server
  newName: k8s.gcr.io/metrics-server/metrics-server
  newTag: v0.5.0
