apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::177337816322:role/aim-city_kube-system_external-secrets
  labels:
    name: kubernetes-external-secrets
