apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-rds-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::177337816322:role/aim-city_external_secret_kubeflow
  data:
  - key: aim-city/kubeflow/rds_username
    name: RDS_USERNAME
  - key: aim-city/kubeflow/rds_password
    name: RDS_PASSWORD
