kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-s3-config
  namespace: kubeflow
data:
  REGION: us-east-1
  BUCKET_NAME: 177337816322-aim-city-pipelines
  PIPELINE_FOLDER: pipelines
  PIPELINE_PATH: pipelines
