apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::177337816322:role/aim-city_external_secret_kubeflow
  data:
  - key: aim-city/kubeflow/s3_accesskey
    name: S3_ACCESSKEY
  - key: aim-city/kubeflow/s3_secretkey
    name: S3_SECRETKEY
