apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.kubeflow__>>
  data:
  - key: <<__external_secret_name.kubeflow.s3_accesskey__>>
    name: S3_ACCESSKEY
  - key: <<__external_secret_name.kubeflow.s3_secretkey__>>
    name: S3_SECRETKEY
