apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: auth-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: auth.platform.aflr.io
  dnsNames:
    - auth.platform.aflr.io
