apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
spec:
  project: default
  source:
    chart: oauth2-proxy
    helm:
      parameters:
      - name: image.repository
        value: quay.io/oauth2-proxy/oauth2-proxy
      - name: image.tag
        value: v7.1.3
      - name: configSecret.create
        value: 'false'
      - name: config.existingSecret
        value: oauth2-proxy
      - name: service.port
        value: '4180'
      - name: extraArgs.provider
        value: oidc
      - name: extraArgs.set-xauthrequest
        value: 'true'
      - name: extraArgs.cookie-secure
        value: 'true'
      - name: extraArgs.cookie-samesite
        value: lax
      - name: extraArgs.cookie-refresh
        value: 1h
      - name: extraArgs.cookie-expire
        value: 4h
      - name: extraArgs.cookie-name
        value: _oauth2_proxy
      - name: extraArgs.email-domain
        value: '*'
      - name: extraArgs.upstream
        value: static://200
      - name: extraArgs.skip-provider-button
        value: 'true'
      - name: extraArgs.cookie-domain
        value: .aim-city.pub.aws.mitre.org
      - name: extraArgs.whitelist-domain
        value: .aim-city.pub.aws.mitre.org
      - name: extraArgs.oidc-issuer-url
        value: https://gitlab.my-company.com
      - name: extraArgs.scope
        value: openid profile email
      - name: extraArgs.user-id-claim
        value: email
      - name: serviceAccount.enabled
        value: 'false'   # we will create the ServiceAccount manually.
      - name: serviceAccount.name
        value: oauth2-proxy
      - name: sessionStorage.type
        value: redis
      - name: sessionStorage.redis.standalone.clientType
        value: standalone
      - name: sessionStorage.redis.standalone.connectionUrl
        value: redis://aim-city-redis.uk2cvk.ng.0001.use1.cache.amazonaws.com:6379
    repoURL: https://oauth2-proxy.github.io/manifests
    targetRevision: 3.3.2
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
