apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.auth__>>
  data:
  - key: <<__external_secret_name.auth.oidc_client_id__>>
    name: client-id
  - key: <<__external_secret_name.auth.oidc_client_secret__>>
    name: client-secret
  - key: <<__external_secret_name.auth.oidc_cookie_secret__>>
    name: cookie-secret
