apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateways-issuer
spec:  
  selfSigned:
    $patch: delete
  acme:
    email: <<__cert_manager.email_user__>>@<<__cert_manager.email_domain__>>
    server: <<__cert_manager.server__>>
    privateKeySecretRef:
      name: gateways-issuer-account-key
    solvers:
    - dns01:
        route53:
          hostedZoneID: <<__route53.hosted_zone_id__>>
          region: eu-west-1
          # role: <<__role_arn.cert_manager__>>
