apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.1.6
    chart: aws-load-balancer-controller
    helm:
      parameters:
        - name: "rbac.serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
          value: SETUP_CONF.ROLE_ARN_LOADBALANCER_CONTROLLER
        - name: clusterName
          value: SETUP_CONF.CLUSTER_NAME
        - name: vpcId
          value: SETUP_CONF.VPC_ID
        - name: region
          value: SETUP_CONF.AWS_REGION
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
