apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-eks-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    path: distribution/aws-eks-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
