apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-dns
    helm:
      parameters:
        - name: aws.region
          value: << aws_region >>
        - name: domainFilters[0]
          value: << domain >>
        - name: rbac.create
          value: "true"
        - name: resources.limits.cpu
          value: 100m
        - name: resources.limits.memory
          value: 300Mi
        - name: resources.requests.cpu
          value: 100m
        - name: resources.requests.memory
          value: 300Mi
        - name: serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn
          value: << role_arn.external_dns >>
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 3.4.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
