apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-dns
    helm:
      parameters:
      - name: aws.region
        value: <<__aws_region__>>
      - name: domainFilters[0]
        value: <<__route53.hosted_zone_domain__>>
      - name: serviceAccount.create
        value: 'true'
      - name: rbac.create
        value: 'true'
      - name: resources.limits.cpu
        value: 100m
      - name: resources.limits.memory
        value: 300Mi
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 300Mi
      - name: sources[0]
        value: service
      - name: sources[1]
        value: ingress
      - name: sources[2]
        value: istio-gateway
      - name: sources[3]
        value: istio-virtualservice
      # - name: aws.assumeRolenArn
      #   value: <<__role_arn.external_dns__>>
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: <<__role_arn.external_dns__>>
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.0.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
