apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfserving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ReggieCarey/argoflow-aws.git
    targetRevision: 177337816322/aim-city.pub.aws.mitre.org
    path: distribution/kubeflow/kfserving
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
