apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ReggieCarey/argoflow-aws.git
    targetRevision: 177337816322/aim-city.pub.aws.mitre.org
    path: distribution/oidc-auth/overlays/keycloak
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
