apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pod-defaults
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    path: distribution/kubeflow/notebooks/pod-defaults
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
