apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xgboost-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <<conf.git_repo.url.conf>>
    targetRevision: <<conf.git_repo.target_revision.conf>>
    path: distribution/kubeflow/operators/xgboost
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
