---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: argo
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kubeflow-pipelines-viewer
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-pipeline
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-pipeline-persistenceagent
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-pipeline-scheduledworkflow
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-pipeline-ui
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-pipeline-viewer-crd-service-account
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ml-pipeline-visualizationserver
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline-runner
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.pipelines__>>
