apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: mlflow
spec:
  backendType: secretsManager
  roleArn: <<conf.role_arn.external_secrets.mlflow.conf>>
  data:
    - key: <<conf.external_secret_name.mlflow.rds_username.conf>>
      name: RDS_USERNAME
    - key: <<conf.external_secret_name.mlflow.rds_password.conf>>
      name: RDS_PASSWORD
