apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-secret
  namespace: mlflow
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.mlflow__>>
  data:
  - key: <<__external_secret_name.mlflow.rds_username__>>
    name: RDS_USERNAME
  - key: <<__external_secret_name.mlflow.rds_password__>>
    name: RDS_PASSWORD
