apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: mlflow
spec:
  backendType: secretsManager
  roleArn: <SETUP_CONF.ROLE_ARN.EXTERNAL_SECRETS.AWS>
  data:
    - key: <SETUP_CONF.EXTERNAL_SECRET_NAME.MLFLOW.RDS_USERNAME>
      name: RDS_USERNAME
    - key: <SETUP_CONF.EXTERNAL_SECRET_NAME.MLFLOW.RDS_PASSWORD>
      name: RDS_PASSWORD
