apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "LR19NyYi9Y+7TamfTTh3a3PTpaSLvj1A244zvtXQjOB7uO0blR5rdPasT348/LAR\nVl8gh5kf37spGWnEx/tct0NCm6uCIbuYwPqSFZwRrsgCoxtYw5Q7EmbCyXWiH4rK\n+l12FojMqYua71voti0d0GZx4rvUL/NIqUbfp4mS14g="
