apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "18OrQ7UQwkx3lnJPqmg6yaE3m1avsffIJ87TKHnaaTKHLXuRoK3Ips34Gs3piUH/\nbnamboP4ad9PecR6wikckjuFw+/sARkC51hgyyL367LeGPIj/hA++yUJihWVUhky\n7dLvV9fIMR7UsQxCnW730+ozTdtvuvlkwqMzqQ2gLmc="
