apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: katib-rds-secret
  namespace: kubeflow
spec:
  backendType: secretsManager
  roleArn: <<__role_arn.external_secrets.kubeflow__>>
  data:
  - key: <<__external_secret_name.kubeflow.rds_username__>>
    name: RDS_USERNAME
  - key: <<__external_secret_name.kubeflow.rds_password__>>
    name: RDS_PASSWORD
