apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflow-pipelines-profile-controller
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: profile-controller
        command: [python, /hooks/sync_with_s3.py]
        env:
        - name: SECRET_NAME_S3_ACCESSKEY
          value: aim-city/kubeflow/s3_accesskey
        - name: SECRET_NAME_S3_SECRETKEY
          value: aim-city/kubeflow/s3_secretkey
        - name: EXTERNAL_SECRET_ROLE_ARN
          value: arn:aws:iam::177337816322:role/aim-city_external_secret_kubeflow
        - name: EXTERNAL_SECRET_BACKEND_TYPE
          value: secretsManager

        # remove minio-related params
        - $patch: delete
          name: MINIO_ACCESS_KEY
        - $patch: delete
          name: MINIO_SECRET_KEY
