kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgCq7ieYc/TWV1KqQcnXj+xuLAX/gyVz4v4Qrmjawhxp5ot9SZnYAXFPusFpTnjcXb4drJqXu689SV1wwTYjvTBYjEoyrRPQLvTNnM/TU88yK6rskHWXsdIkmsjEOQKiAtg29KlF806/FwYpor4U9r/vyJ3Rsw3ZGLLoD9/llUvAGVy9wIWl/zvO8y6FgLxzXkl7/QgX1eoo3P0jeCWumSysMwKuwEHaE5kBsKLC4nVenhFnqOseVr+mEOLsHUXcNIRPyRuEGRAPxztcPJGYAP4gtk7MoagztE3M3u39b+diT02V7Wpg/5rGt7QdgRlTiHpT9VTcQCYsbpQRTUgcOrOTEyMNgMBe4kudBsQsSzKTaN/peZpOZbSOPFRgb9p76Wxol3xwI58BrImOvn3e1jQJvIy0y5EmcVekNLi1ecWpPwKmsWJbirTiOnicNdoUUMo4Mc69s/aC+c7Fv8q6/bclklt59NEW+qSmJLvp1h/jWNYPk5BoRNfRxfmkCbTz3sFnImjitlI+UcpD51tdF/HL0/r/jDvX9aKxiD6c12hYEsGbeVWIuMjKkO1ZipFfEXvdS+PTZ+9QUHlSOSKL/ht2ZY5+sGPsj4AKwsaERZ4l0l/NiRhnGJyToyN1ysTgTI/Ed1YUfwhInpxrumMsptV14frdufRLanUlS230cR5Qaj/kHQNUo7uMOrdvSeSfTXgM9Pe401dJqZ27dkv2Dg==
    admin-user: AgCDSDrHFZUEWtWWKLxQJQ3etBtQrT+Mxk1281esWT2SiBTW83PtK/Ev+paZ6iBrqXr7jsPHpT1d+h72fxbDzWw/X1bGRH0ySBgU6qiF0SheMKx4bWSR5luQMxOQ37aqW/WBojHaiMFPxvvnWJvsHJCAUjajqe0Qkxcy1UEBUjDzYzhLeJ1VjEYsStKsTWU3WSdTc539HHlP3hyJymPtxIsU0tt1YRy641sPlm4vYg+PdMuVPaAHxOs1ni/f+nzsvq6JkHtmVyxe4+/P7QMB+xQ1s6AQsC34kmwQMq3zaKOpK836zXgnEeI2xctyr3HenXNytj5mkXOoaedaMW9UxEBQNZ0QDjNs63vVErf9KYYavLv3EfthXBVymd7SYgGrtvjXG+ls8ttqpidKZifKik0AOjOoTMmeWVC9isq3OUyou7lK9JBeJmchzFjU62IYUjWV+dtkNQC9vtbVgxz/V0ucC7LXBRlRPSxZZe1J+5vEapH0loWBJ7qFSHJtEBeGTVpb7k4F4643aud5/Q8usZycyxuhWmAOK8QvWfICC6W6RhUC972JzkTg+aWmwM6aI9LbtvXV35Qkz0c7967v5fRH2qslLrSaKsHRGuQD18KYLode1bclWbTUDogKX0rg6CMyZxFVMCocioRO2cN0VXjLDbMJz17K/Sl9ZDYQLS0TFn8anfibjldqw3BPDif9UkdCNW8sBoU=
